name: Deploy with Docker

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./8StreamApi
          file: ./8StreamApi/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/chilingzone:latest
            ghcr.io/${{ github.repository }}/chilingzone:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NODE_ENV=production
            TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}
            
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            docker pull ghcr.io/${{ github.repository }}/chilingzone:latest
            docker stop chilingzone || true
            docker rm chilingzone || true
            docker run -d \
              --name chilingzone \
              --restart unless-stopped \
              -p 3000:3000 \
              -e NODE_ENV=production \
              -e TMDB_API_KEY=${{ secrets.TMDB_API_KEY }} \
              ghcr.io/${{ github.repository }}/chilingzone:latest 